services:
  - type: web
    name: lekzy-fx-ai-pro
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: your_telegram_bot_token
      - key: ADMIN_TOKEN
        value: your_admin_password
      - key: RENDER
        value: true
